import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

// Start of custom components
// Card related
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import { CardActionArea, Container } from "@mui/material";
import Stack from "@mui/material/Stack";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* I would like to add a simple 3D animation created by three.js here. That should be quite a enticing landing page */}
        <Container maxWidth="md">
          <Stack direction="row" spacing={2}>
            <Card sx={{ maxWidth: 345, flex: 1 }}>
              <CardActionArea>
                <CardMedia
                  component="img"
                  height="140"
                  image="/static/images/buy.jpg"
                  alt="green iguana"
                />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    Buy a car
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Browse our list to find your next dream car!
                  </Typography>
                </CardContent>
              </CardActionArea>
            </Card>
            <Card sx={{ maxWidth: 345, flex: 1 }}>
              <CardActionArea>
                <CardMedia
                  component="img"
                  height="140"
                  image="/static/images/buy.jpg"
                  alt="green iguana"
                />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    Sell a car
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Want to sell your car? We got you covered!
                  </Typography>
                </CardContent>
              </CardActionArea>
            </Card>
            <Card sx={{ maxWidth: 345, flex: 1 }}>
              <CardActionArea>
                <CardMedia
                  component="img"
                  height="140"
                  image="/static/images/buy.jpg"
                  alt="green iguana"
                />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    Rent a car
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Wanted to try out a car before buying it? You can rent one to experience it yourself!
                  </Typography>
                </CardContent>
              </CardActionArea>
            </Card>
          </Stack>
        </Container>
      </main>
    </>
  );
}
